
const $vertodos = document.querySelector("#vertodos");
const $embutidos = document.querySelector("#embutidos");
const $cortes = document.querySelector("#cortes");
const $anchuras = document.querySelector("#anchuras");
const $extras = document.querySelector("#extras");

const $costillarCompleto = document.querySelector("#costillar-completo");
const $vacio = document.querySelector("#vacio");
const $tapaAsado = document.querySelector("#tapaAsado");
const $tiraCostilla = document.querySelector("#tiraCostilla");
const $mollejas = document.querySelector("#mollejas");
const $chinchulines = document.querySelector("#chinchulines");
const $matambreRes = document.querySelector("#matambreRes");
const $matambreCerdo = document.querySelector("#matambreCerdo");
const $entraña = document.querySelector("#entraña");
const $matambreArrollado = document.querySelector("#matambreArrollado");
const $choricitos = document.querySelector("#choricitos");
const $morcilla = document.querySelector("#morcilla");
const $salamines = document.querySelector("#salamines");
const $bondiola = document.querySelector("#bondiola");
const $chimichurri = document.querySelector("#chimichurri");
const $Rinones = document.querySelector("#Rinones");
const $Longaniza = document.querySelector("#Longaniza");
const $Panceta = document.querySelector("#Panceta");
const $JamonSerrano = document.querySelector("#JamonSerrano");


$vertodos.onclick = function vertodos(){
    $costillarCompleto.classList.add("articulo");
    $costillarCompleto.classList.remove("articulo-borrado");
    $vacio.classList.add("articulo");
    $vacio.classList.remove("articulo-borrado");
    $tapaAsado.classList.add("articulo");
    $tapaAsado.classList.remove("articulo-borrado");
    $tiraCostilla.classList.add("articulo");
    $tiraCostilla.classList.remove("articulo-borrado");
    $mollejas.classList.add("articulo");
    $mollejas.classList.remove("articulo-borrado");
    $chinchulines.classList.add("articulo");
    $chinchulines.classList.remove("articulo-borrado");
    $matambreRes.classList.add("articulo");
    $matambreRes.classList.remove("articulo-borrado");
    $matambreCerdo.classList.add("articulo");
    $matambreCerdo.classList.remove("articulo-borrado");
    $entraña.classList.add("articulo");
    $entraña.classList.remove("articulo-borrado");
    $matambreArrollado.classList.add("articulo");
    $matambreArrollado.classList.remove("articulo-borrado");
    $choricitos.classList.add("articulo");
    $choricitos.classList.remove("articulo-borrado");
    $morcilla.classList.add("articulo");
    $morcilla.classList.remove("articulo-borrado");
    $salamines.classList.add("articulo");
    $salamines.classList.remove("articulo-borrado");
    $bondiola.classList.add("articulo");
    $bondiola.classList.remove("articulo-borrado");
    $chimichurri.classList.add("articulo");
    $chimichurri.classList.remove("articulo-borrado");
    $Rinones.classList.add("articulo");
    $Rinones.classList.remove("articulo-borrado");
    $Longaniza.classList.add("articulo");
    $Longaniza.classList.remove("articulo-borrado");
    $Panceta.classList.add("articulo");
    $Panceta.classList.remove("articulo-borrado");
    $JamonSerrano.classList.add("articulo");
    $JamonSerrano.classList.remove("articulo-borrado");
}
$embutidos.onclick = function embutidos(){
    $costillarCompleto.classList.remove("articulo");
    $costillarCompleto.classList.add("articulo-borrado");
    $vacio.classList.remove("articulo");
    $vacio.classList.add("articulo-borrado");
    $tapaAsado.classList.remove("articulo");
    $tapaAsado.classList.add("articulo-borrado");
    $tiraCostilla.classList.remove("articulo");
    $tiraCostilla.classList.add("articulo-borrado");
    $mollejas.classList.remove("articulo");
    $mollejas.classList.add("articulo-borrado");
    $chinchulines.classList.remove("articulo");
    $chinchulines.classList.add("articulo-borrado");
    $matambreRes.classList.remove("articulo");
    $matambreRes.classList.add("articulo-borrado");
    $matambreCerdo.classList.remove("articulo");
    $matambreCerdo.classList.add("articulo-borrado");
    $entraña.classList.remove("articulo");
    $entraña.classList.add("articulo-borrado");
    $matambreArrollado.classList.remove("articulo");
    $matambreArrollado.classList.add("articulo-borrado");
    $choricitos.classList.add("articulo");
    $choricitos.classList.remove("articulo-borrado");
    $morcilla.classList.add("articulo");
    $morcilla.classList.remove("articulo-borrado");
    $salamines.classList.add("articulo");
    $salamines.classList.remove("articulo-borrado");
    $bondiola.classList.add("articulo");
    $bondiola.classList.remove("articulo-borrado");
    $chimichurri.classList.remove("articulo");
    $chimichurri.classList.add("articulo-borrado");
    $Rinones.classList.remove("articulo");
    $Rinones.classList.add("articulo-borrado");
    $Panceta.classList.remove("articulo");
    $Panceta.classList.add("articulo-borrado");
    $Longaniza.classList.add("articulo");
    $Longaniza.classList.remove("articulo-borrado");
    $JamonSerrano.classList.add("articulo");
    $JamonSerrano.classList.remove("articulo-borrado");
}
$cortes.onclick = function cortes(){
    $costillarCompleto.classList.add("articulo");
    $costillarCompleto.classList.remove("articulo-borrado");
    $vacio.classList.add("articulo");
    $vacio.classList.remove("articulo-borrado");
    $tapaAsado.classList.add("articulo");
    $tapaAsado.classList.remove("articulo-borrado");
    $tiraCostilla.classList.add("articulo");
    $tiraCostilla.classList.remove("articulo-borrado");
    $mollejas.classList.remove("articulo");
    $mollejas.classList.add("articulo-borrado");
    $chinchulines.classList.remove("articulo");
    $chinchulines.classList.add("articulo-borrado");
    $matambreRes.classList.add("articulo");
    $matambreRes.classList.remove("articulo-borrado");
    $matambreCerdo.classList.add("articulo");
    $matambreCerdo.classList.remove("articulo-borrado");
    $entraña.classList.remove("articulo");
    $entraña.classList.add("articulo-borrado");
    $matambreArrollado.classList.add("articulo");
    $matambreArrollado.classList.remove("articulo-borrado");
    $choricitos.classList.remove("articulo");
    $choricitos.classList.add("articulo-borrado");
    $morcilla.classList.remove("articulo");
    $morcilla.classList.add("articulo-borrado");
    $salamines.classList.remove("articulo");
    $salamines.classList.add("articulo-borrado");
    $bondiola.classList.remove("articulo");
    $bondiola.classList.add("articulo-borrado");
    $chimichurri.classList.remove("articulo");
    $chimichurri.classList.add("articulo-borrado");
    $Rinones.classList.remove("articulo");
    $Rinones.classList.add("articulo-borrado");    
    $Longaniza.classList.remove("articulo");
    $Longaniza.classList.add("articulo-borrado");
    $JamonSerrano.classList.remove("articulo");
    $JamonSerrano.classList.add("articulo-borrado");
}
$anchuras.onclick = function anchuras(){
    $costillarCompleto.classList.remove("articulo");
    $costillarCompleto.classList.add("articulo-borrado");
    $vacio.classList.remove("articulo");
    $vacio.classList.add("articulo-borrado");
    $tapaAsado.classList.remove("articulo");
    $tapaAsado.classList.add("articulo-borrado");
    $tiraCostilla.classList.remove("articulo");
    $tiraCostilla.classList.add("articulo-borrado");
    $mollejas.classList.add("articulo");
    $mollejas.classList.remove("articulo-borrado");
    $chinchulines.classList.add("articulo");
    $chinchulines.classList.remove("articulo-borrado");
    $matambreRes.classList.remove("articulo");
    $matambreRes.classList.add("articulo-borrado");
    $matambreCerdo.classList.remove("articulo");
    $matambreCerdo.classList.add("articulo-borrado");
    $entraña.classList.add("articulo");
    $entraña.classList.remove("articulo-borrado");
    $matambreArrollado.classList.remove("articulo");
    $matambreArrollado.classList.add("articulo-borrado");
    $choricitos.classList.remove("articulo");
    $choricitos.classList.add("articulo-borrado");
    $morcilla.classList.remove("articulo");
    $morcilla.classList.add("articulo-borrado");
    $salamines.classList.remove("articulo");
    $salamines.classList.add("articulo-borrado");
    $bondiola.classList.remove("articulo");
    $bondiola.classList.add("articulo-borrado");
    $chimichurri.classList.remove("articulo");
    $chimichurri.classList.add("articulo-borrado");
    $Rinones.classList.add("articulo");
    $Rinones.classList.remove("articulo-borrado");
    $Longaniza.classList.remove("articulo");
    $Longaniza.classList.add("articulo-borrado");
    $Panceta.classList.remove("articulo");
    $Panceta.classList.add("articulo-borrado");
    $JamonSerrano.classList.remove("articulo");
    $JamonSerrano.classList.add("articulo-borrado");
}
$extras.onclick = function extras(){
    $costillarCompleto.classList.remove("articulo");
    $costillarCompleto.classList.add("articulo-borrado");
    $vacio.classList.remove("articulo");
    $vacio.classList.add("articulo-borrado");
    $tapaAsado.classList.remove("articulo");
    $tapaAsado.classList.add("articulo-borrado");
    $tiraCostilla.classList.remove("articulo");
    $tiraCostilla.classList.add("articulo-borrado");
    $mollejas.classList.remove("articulo");
    $mollejas.classList.add("articulo-borrado");
    $chinchulines.classList.remove("articulo");
    $chinchulines.classList.add("articulo-borrado");
    $matambreRes.classList.remove("articulo");
    $matambreRes.classList.add("articulo-borrado");
    $matambreCerdo.classList.remove("articulo");
    $matambreCerdo.classList.add("articulo-borrado");
    $entraña.classList.remove("articulo");
    $entraña.classList.add("articulo-borrado");
    $matambreArrollado.classList.remove("articulo");
    $matambreArrollado.classList.add("articulo-borrado");
    $choricitos.classList.remove("articulo");
    $choricitos.classList.add("articulo-borrado");
    $morcilla.classList.remove("articulo");
    $morcilla.classList.add("articulo-borrado");
    $salamines.classList.remove("articulo");
    $salamines.classList.add("articulo-borrado");
    $bondiola.classList.remove("articulo");
    $bondiola.classList.add("articulo-borrado");
    $chimichurri.classList.add("articulo");
    $chimichurri.classList.remove("articulo-borrado");
    $Rinones.classList.remove("articulo");
    $Rinones.classList.add("articulo-borrado");
    $Longaniza.classList.remove("articulo");
    $Longaniza.classList.add("articulo-borrado");
    $Panceta.classList.remove("articulo");
    $Panceta.classList.add("articulo-borrado");
    $JamonSerrano.classList.remove("articulo");
    $JamonSerrano.classList.add("articulo-borrado");
}
$CuradoSal.onclick = function CuradoSal(){
    $bondiola.classList.add("articulo");
    $bondiola.classList.remove("articulo-borrado");
    $Panceta.classList.add("articulo");
    $Panceta.classList.remove("articulo-borrado");
}